//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enemy
    {
        public int EnemyId { get; set; }
        public string EnemyName { get; set; }
        public Nullable<int> EnemyRace { get; set; }
        public Nullable<int> EnemyClass { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Race Race { get; set; }
    }
}
