//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrpDatabaseEntities : DbContext
    {
        public FrpDatabaseEntities()
            : base("name=FrpDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Counties> Counties { get; set; }
        public virtual DbSet<Enemy> Enemy { get; set; }
        public virtual DbSet<GameStory> GameStory { get; set; }
        public virtual DbSet<Npc> Npc { get; set; }
        public virtual DbSet<Race> Race { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesForms> RolesForms { get; set; }
        public virtual DbSet<UserChoose> UserChoose { get; set; }
        public virtual DbSet<UserInRoles> UserInRoles { get; set; }
        public virtual DbSet<UserRegister> UserRegister { get; set; }
    }
}
