//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChoose
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserChoose()
        {
            this.UserRegister1 = new HashSet<UserRegister>();
        }
    
        public int UserChooseId { get; set; }
        public Nullable<int> UserChooseRace { get; set; }
        public Nullable<int> UserChooseClass { get; set; }
        public Nullable<int> CUserId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Race Race { get; set; }
        public virtual UserRegister UserRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRegister> UserRegister1 { get; set; }
    }
}
